### ISSUE TITLE
Template not found during load of published map

### ISSUE THREAD

**Issue by nballenger** [ruralinnovation/multi-svc-cartodb#4]
Errors from the JavaScript console in Chrome:

```
common_vendor.js:152277 Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error
    at checkDeprecatedMixinEvents (https://nick.localhost/assets/1.0.0-assets.88/javascripts/common_vendor.js:152279:47)
    at Function.push../node_modules/leaflet/dist/leaflet-src.js.Class.extend (https://nick.localhost/assets/1.0.0-assets.88/javascripts/common_vendor.js:152207:3)
    at Object../node_modules/internal-carto.js/node_modules/torque.js/lib/torque/leaflet/canvas_layer.js (https://nick.localhost/assets/1.0.0-assets.88/javascripts/common_vendor.js:103823:25)
    at __webpack_require__ (https://nick.localhost/assets/1.0.0-assets.88/javascripts/builder_embed.js:79:30)
    at Object.<anonymous> (https://nick.localhost/assets/1.0.0-assets.88/javascripts/common_vendor.js:104260:1)
    at Object../node_modules/internal-carto.js/node_modules/torque.js/lib/torque/leaflet/torque.js (https://nick.localhost/assets/1.0.0-assets.88/javascripts/common_vendor.js:104789:30)
    at __webpack_require__ (https://nick.localhost/assets/1.0.0-assets.88/javascripts/builder_embed.js:79:30)
    at Object../node_modules/internal-carto.js/node_modules/torque.js/lib/torque/leaflet/index.js (https://nick.localhost/assets/1.0.0-assets.88/javascripts/common_vendor.js:104084:5)
    at __webpack_require__ (https://nick.localhost/assets/1.0.0-assets.88/javascripts/builder_embed.js:79:30)
    at Object../node_modules/internal-carto.js/node_modules/torque.js/lib/torque/index.js (https://nick.localhost/assets/1.0.0-assets.88/javascripts/common_vendor.js:103799:1)
checkDeprecatedMixinEvents @ common_vendor.js:152277
common_vendor.js:116617 carto.js 4.1.11-0
common_vendor.js:178203 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2019-05-15 19:19:30 UTC, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (https://nick.localhost/assets/1.0.0-assets.88/javascripts/common_vendor.js:178230:94)
    at configFromString (https://nick.localhost/assets/1.0.0-assets.88/javascripts/common_vendor.js:180088:11)
    at configFromInput (https://nick.localhost/assets/1.0.0-assets.88/javascripts/common_vendor.js:180457:9)
    at prepareConfig (https://nick.localhost/assets/1.0.0-assets.88/javascripts/common_vendor.js:180440:9)
    at createFromConfig (https://nick.localhost/assets/1.0.0-assets.88/javascripts/common_vendor.js:180407:40)
    at createLocalOrUTC (https://nick.localhost/assets/1.0.0-assets.88/javascripts/common_vendor.js:180494:12)
    at createLocal (https://nick.localhost/assets/1.0.0-assets.88/javascripts/common_vendor.js:180498:12)
    at hooks (https://nick.localhost/assets/1.0.0-assets.88/javascripts/common_vendor.js:177926:25)
    at child.render (https://nick.localhost/assets/1.0.0-assets.88/javascripts/common.js:50587:20)
    at child.render (https://nick.localhost/assets/1.0.0-assets.88/javascripts/common.js:50888:28)
warn @ common_vendor.js:178203
builder_embed.js:913 Dashboard has some errors: Error: Template 'tpl_d2870a2b_f042_447f_a9b3_748baadf1f63' of user 'nick' not found
    at Object.error (common.js:50164)
    at Object.error (common_vendor.js:131582)
    at common_vendor.js:119711
    at Array.forEach (<anonymous>)
    at Engine.<anonymous> (common_vendor.js:119710)
(anonymous) @ builder_embed.js:913
common_vendor.js:119712 Uncaught (in promise) WindshaftErrorcontext: undefinedmessage: "Template 'tpl_d2870a2b_f042_447f_a9b3_748baadf1f63' of user 'nick' not found"origin: "windshaft"subtype: undefinedtype: "unknown"_error: {type: "unknown", message: "Template 'tpl_d2870a2b_f042_447f_a9b3_748baadf1f63' of user 'nick' not found"}__proto__: Object
embed:1 This site does not have a valid SSL certificate! Without SSL, your site's and visitors' data is vulnerable to theft and tampering. Get a valid SSL certificate before releasing your website to the public.
```

**Comment by nballenger** [comment]
This is fixed, by updating the `tiler.internal` section of the `app_config.yml` to hit the `windshaft` container directly, over HTTP. This is similar to a fix discussed in issue 22 on the sverhoeven repo:

https://github.com/sverhoeven/docker-cartodb/issues/22#issuecomment-492396542
