### ISSUE TITLE
Windshaft exits with error Cannot find module 'millstone'

### ISSUE THREAD

**Issue by sindile** [ruralinnovation/multi-svc-cartodb#49]
I really like this project - pity I am unable to contribute to the project at this stage, hoping to so in the future.
Windshaft container has status Exit 1 - any ideas what could be the issue

Starting the Windshaft node application...
Logs will be written to /carto/Windshaft-cartodb/logs/windshaft.log
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'millstone'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/carto/Windshaft-cartodb/node_modules/grainstore/lib/grainstore/mml-builder/mml-builder-inline.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by nballenger** [comment]
This was being caused because, for whatever reason, you have to do two sequential calls to `npm install`, and I was only making one. Corrected in e88acae12da141187aed413e6a492cc875b5dfe2.
