### ISSUE TITLE
Data import failing

### ISSUE THREAD

**Issue by nballenger** [ruralinnovation/multi-svc-cartodb#7]
File uploaded from local successfully makes it to the public folder, and the job is recognized by the Importer/Resque, but Resque reports the following error:

```
** [15:21:48 2019-05-24] 64: resque-1.25.2: Waiting for imports,exports,users,user_dbs,geocodings,synchronizations,tracker,user_migrations,batch_updates,gears
** [15:21:53 2019-05-24] 64: Checking imports
** [15:21:53 2019-05-24] 64: Found job on imports
** [15:21:53 2019-05-24] 64: got: (Job{imports} | Resque::ImporterJobs | [{"job_id"=>"70e6618e-e4d0-4872-af50-79887f10ad49"}])
** [15:21:53 2019-05-24] 64: resque-1.25.2: Processing imports since 1558711313 [Resque::ImporterJobs]
** [15:21:53 2019-05-24] 64: Running before_fork hooks with [(Job{imports} | Resque::ImporterJobs | [{"job_id"=>"70e6618e-e4d0-4872-af50-79887f10ad49"}])]
** [15:21:53 2019-05-24] 64: resque-1.25.2: Forked 124 at 1558711313
** [15:21:53 2019-05-24] 124: Running after_fork hooks with [(Job{imports} | Resque::ImporterJobs | [{"job_id"=>"70e6618e-e4d0-4872-af50-79887f10ad49"}])]
D, [2019-05-24T15:21:53.300700 #124] DEBUG -- :   ^[[1m^[[36mCarto::User Load (2.0ms)^[[0m  ^[[1mSELECT  "users".* FROM "users" WHERE "users"."id" = '6faf0dea-45eb-4267-b655-5a42860c1d55' LIMIT 1^[[0m  [["id", "6faf0dea-45eb-4267-b655-5a42860c1d55"]]
resque-1.25.2: Processing imports since 1558711313 [Resque::ImporterJobs]: No such file or directory - addr
E, [2019-05-24T15:21:53.436395 #124] ERROR -- : error: Import error
#<NoMethodError: undefined method `[]' for nil:NilClass>
/var/lib/gems/2.5.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:603:in `block (2 levels) in first_mac'
/var/lib/gems/2.5.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:602:in `map'
/var/lib/gems/2.5.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:602:in `block in first_mac'
/var/lib/gems/2.5.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:608:in `first_mac'
/var/lib/gems/2.5.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:634:in `mac_address'
/var/lib/gems/2.5.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:242:in `block in timestamp_create'
/var/lib/gems/2.5.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:232:in `synchronize'
/var/lib/gems/2.5.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:232:in `timestamp_create'
/carto/cartodb/services/importer/lib/importer/job.rb:13:in `initialize'
/carto/cartodb/services/importer/lib/importer/runner.rb:414:in `new'
/carto/cartodb/services/importer/lib/importer/runner.rb:414:in `new_job'
/carto/cartodb/services/importer/lib/importer/runner.rb:53:in `initialize'
/carto/cartodb/app/models/data_import.rb:785:in `new'
/carto/cartodb/app/models/data_import.rb:785:in `new_importer_with_runner'
/carto/cartodb/app/models/data_import.rb:736:in `new_importer'
/carto/cartodb/app/models/data_import.rb:423:in `dispatch'
/carto/cartodb/app/models/data_import.rb:189:in `run_import!'
/carto/cartodb/lib/resque/importer_jobs.rb:9:in `block in perform'
/carto/cartodb/lib/resque/base_job.rb:21:in `run_action'
/carto/cartodb/lib/resque/importer_jobs.rb:9:in `perform'
/var/lib/gems/2.5.0/gems/resque-1.25.2/lib/resque/job.rb:240:in `block (3 levels) in perform'
/var/lib/gems/2.5.0/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `around_perform_metrics'
/var/lib/gems/2.5.0/gems/resque-1.25.2/lib/resque/job.rb:239:in `block (2 levels) in perform'
/var/lib/gems/2.5.0/gems/resque-1.25.2/lib/resque/job.rb:247:in `perform'
/var/lib/gems/2.5.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'
/var/lib/gems/2.5.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'
/var/lib/gems/2.5.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'
/var/lib/gems/2.5.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'
/var/lib/gems/2.5.0/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.5.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/var/lib/gems/2.5.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/var/lib/gems/2.5.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/var/lib/gems/2.5.0/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/var/lib/gems/2.5.0/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/var/lib/gems/2.5.0/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/var/lib/gems/2.5.0/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/var/lib/gems/2.5.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/var/lib/gems/2.5.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/var/lib/gems/2.5.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/var/lib/gems/2.5.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/var/lib/gems/2.5.0/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/var/lib/gems/2.5.0/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/var/lib/gems/2.5.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/var/lib/gems/2.5.0/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/var/lib/gems/2.5.0/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
```

**Comment by nballenger** [comment]
This is fixed. Sadly I cannot remember exactly what fixed it. Binary changesets for testing fixes are...difficult at this time.
